### ISSUE TITLE
[massive-design-error] php-fmt fails unless PHP 7 is installed due to unnecessary code changes

### ISSUE THREAD

**Issue by ioncube** [phpfmt/fmt#137]
First off, php-fmt is great, and when used with sublime it works well, however finding after an auto update in sublime that code can no longer be formatted unless PHP 7 is installed is not good _at all_.

Looking at the codebase it seems that this comes from adding in the use of strong typing. This makes sense for some new projects, but in a mature project the benefit is probably nil, increases the chance of bugs, and causes a waste of time for each and every user that has to make changes to their system as a result. If the php-fmt project was so flakey and unstable that it needed this in a desperate attempt to catch bugs then that could be a justification, but it is neither of those. php-fmt is popular, and lost productivity amounting to many thousands of hours globally at a cost of many more thousands of USD will be the result of this, making it a massively poor decision. 

I applaud and greatly appreciate the dedication to the project, but having a popular project also comes with a certain burden of responsibility; one has to consider the impact on end users of every change made to the codebase, put aside the temptation to tinker, and only make changes that break the uninterrupted ability to use the project if these are either fixing a security problem or a show stopper bug.

**Comment by ccirello** [comment]
The introduction of strong typing already yielded benefits, among them the exposure of bugs. You can always pin an older version. That's why I did a major version bump, those who need either the stability or older PHP version can rollback to an older version and pin it (aka manual installation). 

So the massive loss is not there. It is just result of people not knowing their tools properly. 

I suggest you to switch to php-cs-fixer. They support older versions until PHP 5.3.
